/*
  Self-hosts fonts (no CDN). Copies the OFL-licensed Vazirmatn variable font from npm,
  then generates src/css/generated/fonts.css from whatever is in static/fonts/.
  To use IRANYekanX: put IRANYekanX-Variable.woff2 in static/fonts/ (license permitting) and rebuild.
*/
import fs from 'node:fs';
import path from 'node:path';
import { ROOT } from './lib.mjs';

const fontsDir = path.join(ROOT, 'static/fonts');
fs.mkdirSync(fontsDir, { recursive: true });

const vazir = path.join(ROOT, 'node_modules/vazirmatn');
fs.copyFileSync(path.join(vazir, 'fonts/webfonts/Vazirmatn[wght].woff2'), path.join(fontsDir, 'Vazirmatn-Variable.woff2'));
fs.copyFileSync(path.join(vazir, 'OFL.txt'), path.join(fontsDir, 'Vazirmatn-OFL.txt'));

const faces = [
  { family: 'IRANYekanX', file: 'IRANYekanX-Variable.woff2', weight: '100 1000' },
  { family: 'Vazirmatn', file: 'Vazirmatn-Variable.woff2', weight: '100 900' }
];

const css = ['/* GENERATED by scripts/copy-fonts.mjs - do not edit. */'];
for (const face of faces) {
  if (!fs.existsSync(path.join(fontsDir, face.file))) continue;
  css.push(`@font-face {
  font-family: "${face.family}";
  src: url("../../fonts/${face.file}") format("woff2");
  font-weight: ${face.weight};
  font-style: normal;
  font-display: swap;
}`);
}

const outDir = path.join(ROOT, 'src/css/generated');
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'fonts.css'), css.join('\n\n') + '\n');
console.log(`fonts: ${css.length - 1} @font-face rule(s) generated`);
